# Generated by Django 5.1.6 on 2025-05-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="job",
            table="job",
        ),
    ]
