# Generated by Django 5.1.6 on 2025-05-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_alter_job_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="job",
            name="link",
            field=models.CharField(max_length=200),
        ),
    ]
