# Generated by Django 5.1.6 on 2025-05-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_job_job_description_alter_job_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="link",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
