# Generated by Django 5.1.6 on 2025-06-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_job_company_name_job_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
