# Generated by Django 5.1.6 on 2025-06-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_job_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
