# Generated by Django 5.1.6 on 2025-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0009_alter_job_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
