# Generated by Django 5.1.6 on 2025-05-21 08:07

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job", "0005_alter_job_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position_title",
                    models.CharField(
                        blank=True, db_index=True, max_length=256, null=True
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=256, null=True
                    ),
                ),
                ("job_link", models.URLField(blank=True, null=True)),
                ("status", models.PositiveIntegerField(default=1, null=True)),
                ("applied_date", models.DateTimeField(blank=True, null=True)),
                (
                    "job_description",
                    models.TextField(blank=True, max_length=8192, null=True),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=256, null=True
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "contact_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        region=None,
                    ),
                ),
                ("platform", models.PositiveIntegerField(default=0, null=True)),
                (
                    "comment",
                    models.TextField(
                        blank=True, db_index=True, max_length=8192, null=True
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="job.job"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "application",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "job"), name="u_userjob")
                ],
            },
        ),
    ]
