# Generated by Django 5.1.6 on 2025-05-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_link',
        ),
        migrations.RemoveField(
            model_name='application',
            name='position_title',
        ),
    ]
