# Generated by Django 5.1.6 on 2025-06-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_application_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='platform',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Company website'), (2, 'Indeed'), (3, 'LinkedIn'), (4, 'Undefined')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'Invited'), (4, 'Rejected'), (5, 'Withdrawed'), (6, 'Accepted'), (7, 'Interviewed'), (8, 'Offered')], default=1, null=True),
        ),
    ]
